#!/bin/bash

shopt -s lastpipe

raw() {
    local args=("$@")
    args[0]=${args[0]^^}
    (( ${#args[@]} > 1 )) && args[${#args[@]}-1]=:${args[${#args[@]}-1]}
    printf '%s\r\n' "${args[*]}" >&"$irc_fd"
    (( verbose >= 2 )) && printf '%s==>%s %s\n' "$(tput setaf 1)" "$(tput sgr0)" "${args[*]}" >&2
}

say() {
    raw privmsg "$target" "$*"
}

reply() {
    if (( private )); then
        say "$*"
    else
        say "$sender_nick: $*"
    fi
}

ctcp() {
    local args=("$@")
    args[0]=${args[0]^^}
    raw notice "$target" $'\1'"${args[*]}"$'\1'
}

on_exit() {
    raw quit "$quit_message"
}

IFS=$' \t\n'
verbose=0
config=./config.sh

while getopts :vc: o; do
    case $o in
    v)
        (( verbose++ ))
        ;;
    c)
        config=$OPTARG
        [[ $config == */* ]] || config=./$config
        ;;
    *)
        printf 'usage: %s [-v]...\n' "$0"
        exit 1
        ;;
    esac
done
shift "$(( OPTIND - 1 ))"

url='https://git.monade.li/costello'

nick=costello
user=
realname=
quit_message=""

. "$config" || exit 1
: "${server:?}" "${prefix:?}" "${port:=6667}" "${user:=$nick}" "${realname:=$nick}"

exec {irc_fd}<> /dev/tcp/"$server"/"$port" || exit 1

trap on_exit exit

raw nick "$nick"
raw user "$user" 0 '*' "$realname"

while read -ru "$irc_fd" line; do
    line=${line%$'\r'}
    (( verbose >= 2 )) && printf '%s<==%s %s\n' "$(tput setaf 2)" "$(tput sgr0)" "$line" >&2
    sender= sender_nick=
    args=()
    if [[ $line == :* ]]; then
        sender=${line%% *}
        sender=${sender#:}
        sender_nick=${sender%%!*}
        line=${line#* }
    fi
    while [[ $line == *' '* && $line != :* ]]; do
        args+=("${line%% *}")
        line=${line#* }
    done
    args+=("${line#:}")
    set -- "${args[@]}"
    cmd=$1
    shift
    case ${cmd,,} in
    001)
        [[ $password ]] && raw privmsg NickServ "identify $password"
        raw mode "$nick" -x
        for channel in "${channels[@]}"; do
            raw join "$channel"
        done
        ;;
    ping)
        raw pong "$1"
        ;;
    privmsg)
        target=$1
        message=$2
        private=
        (( verbose >= 1 )) && printf '%sPRIVMSG%s %s <%s> %s\n' "$(tput setaf 2)" "$(tput sgr0)" "$target" "$sender_nick" "$message" >&2
        if [[ $target == $nick ]]; then
            target=$sender_nick
            private=1
        fi
        if (( private )) && [[ $message == $'\1'*$'\1' ]]; then
            message=${message#$'\1'} message=${message%$'\1'}
            read -r ctcp_cmd _ <<< "$message"
            case ${ctcp_cmd,,} in
            version)
                ctcp version "costello ($url)"
                ;;
            esac
        elif [[ $message == "$prefix"* ]]; then
            message=${message#"$prefix"}
            read -r bot_cmd rest <<< "$message"
            case ${bot_cmd,,} in
            help)
                say "Available commands: help. Source at <$url>."
                ;;
            *)
                say "Unknown command: $bot_cmd"
                ;;
            esac
        fi
        ;;
    esac
done
